TapPaymentIntegration/Controllers/TapPaymentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text.Encodings.Web;
using TapPaymentIntegration.Areas.Identity.Data;
using TapPaymentIntegration.Data;
using TapPaymentIntegration.Models;
using TapPaymentIntegration.Models.Card;
using TapPaymentIntegration.Models.UserDTO;
using static Google.Cloud.RecaptchaEnterprise.V1.AccountVerificationInfo.Types;

namespace TapPaymentIntegration.Controllers
{
    public class TapPaymentController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private TapPaymentIntegrationContext _context;
        private readonly IUserStore<ApplicationUser> _userStore;
        private IWebHostEnvironment _environment;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        public TapPaymentController(IWebHostEnvironment Environment, ILogger<HomeController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, TapPaymentIntegrationContext context, IUserStore<ApplicationUser> userStore)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _environment = Environment;
            _context = context;
            _userStore = userStore;
        }
        //Change Card
        public ActionResult ChangeCard()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> ChangeCard(string id)
        {
            var Token = Request.Form.Where(x => x.Key == "Token").FirstOrDefault().Value.ToString();
            if (Token != null)
            {
                //Get Loggedin User Info
                var userinfo = GetCurrentUserAsync().Result;
                var subinfo = _context.subscriptions.Where(x => x.SubscriptionId == userinfo.SubscribeID).FirstOrDefault();
                var countrycode = "";
                if (userinfo.Country == "Bahrain")
                {
                    countrycode = "+973";
                }
                else if (userinfo.Country == "KSA")
                {
                    countrycode = "+966";
                }
                else if (userinfo.Country == "Kuwait")
                {
                    countrycode = "+965";
                }
                else if (userinfo.Country == "UAE")
                {
                    countrycode = "+971";
                }
                else if (userinfo.Country == "Qatar")
                {
                    countrycode = "+974";
                }
                else if (userinfo.Country == "Oman")
                {
                    countrycode = "+968";
                }
                else
                {
                    countrycode = "966";
                }
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Post, "https://api.tap.company/v2/card/verify");
                request.Headers.Add("authorization", "Bearer " + userinfo.SecertKey);
                request.Headers.Add("accept", "application/json");
                var complete_url = Constants.RedirectURL + "TapPayment/ChangeCardResponse";
                var content = new StringContent("{\"currency\":\""+ subinfo.Currency + "\",\"threeDSecure\":true,\"save_card\":true,\"metadata\":{\"udf1\":\"test1\",\"udf2\":\"test2\"},\"customer\":{\"first_name\":\""+userinfo.FullName+"\",\"middle_name\":\"\",\"last_name\":\"\",\"email\":\""+ userinfo.Email+ "\",\"phone\":{\"country_code\":\""+ countrycode + "\",\"number\":\""+userinfo.PhoneNumber+"\"}},\"source\":{\"id\":\""+ Token + "\"},\"redirect\":{\"url\":\""+ complete_url + "\"}}", null, "application/json");
                request.Content = content;
                var response = await client.SendAsync(request);
                var result_erify = await response.Content.ReadAsStringAsync();
                var Deserialized_Deserialized_savecard = JsonConvert.DeserializeObject<VerifyCard>(result_erify);
                HttpContext.Session.SetString("Verify_id", Deserialized_Deserialized_savecard.id);
                return Json(Deserialized_Deserialized_savecard.transaction.url);
            }
            return Json(false);
        }
        public async Task<ActionResult> Deletecardinfo()
        {
            var userinfo = GetCurrentUserAsync().Result;
            DeleteCard Deserialized_savecard = null;
            if (!string.IsNullOrEmpty(userinfo.Tap_CustomerID))
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Delete,
                    RequestUri = new Uri("https://api.tap.company/v2/card/"+ userinfo.Tap_CustomerID+"/"+ userinfo.Tap_Card_ID),
                    Headers =
                              {
                                  { "accept", "application/json" },
                                  { "Authorization","Bearer " + userinfo.SecertKey },
                              },
                };
                using (var response = await client.SendAsync(request))
                {
                    var result = await response.Content.ReadAsStringAsync();
                    Deserialized_savecard = JsonConvert.DeserializeObject<DeleteCard>(result);
                }
            }

            if(Deserialized_savecard.delete == true)
            {

                var invoiceinfo = _context.invoices.Where(x => x.UserId == userinfo.Id).ToList().LastOrDefault();
                var subscriptions = _context.subscriptions.Where(x => x.SubscriptionId == invoiceinfo.SubscriptionId).FirstOrDefault();
                var applicationUser = _context.Users.Where(x => x.Id == invoiceinfo.UserId).FirstOrDefault();

                //Create Invoice
                int days = DateTime.DaysInMonth(DateTime.UtcNow.Year, DateTime.UtcNow.Month);
                decimal finalamount = 0;
                decimal Discount = 0;
                decimal Vat = 0;
                decimal VatwithoutSetupFee = 0;
                if (applicationUser.Frequency == "DAILY")
                {
                    Discount = 0;
                    finalamount = (decimal)Convert.ToInt32(subscriptions.Amount) / (int)days;
                }
                else if (applicationUser.Frequency == "WEEKLY")
                {
                    Discount = 0;
                    finalamount = (decimal)Convert.ToInt32(subscriptions.Amount) / 4;
                }
                else if (applicationUser.Frequency == "MONTHLY")
                {
                    Discount = 0;
                    finalamount = (decimal)Convert.ToInt32(subscriptions.Amount);
                }
                else if (applicationUser.Frequency == "QUARTERLY")
                {
                    Discount = 0;
                    finalamount = (decimal)(Convert.ToInt32(subscriptions.Amount) * 3) / 1;
                }
                else if (applicationUser.Frequency == "HALFYEARLY")
                {
                    Discount = 0;
                    finalamount = (decimal)(Convert.ToInt32(subscriptions.Amount) * 6) / 1;
                }
                else if (applicationUser.Frequency == "YEARLY")
                {
                    decimal amountpercentage = (decimal.Parse(subscriptions.Amount) / 100) * decimal.Parse(subscriptions.Discount);
                    var final_amount_percentage = Convert.ToInt32(subscriptions.Amount) - amountpercentage;
                    finalamount = decimal.Parse(subscriptions.Amount) * 12;
                    Discount = amountpercentage * 12;
                }
                if (subscriptions.VAT == null || subscriptions.VAT == "0")
                {
                    Vat = 0;
                }
                else
                {
                    decimal totala = finalamount + Convert.ToDecimal(subscriptions.SetupFee);
                    Decimal finalTotal = 0;
                    if (Discount != 0)
                    {
                        finalTotal = Decimal.Subtract(totala, Discount);
                        Vat = CalculatePercentage(finalTotal, Convert.ToDecimal(subscriptions.VAT));
                    }
                    else
                    {
                        Vat = CalculatePercentage(totala, Convert.ToDecimal(subscriptions.VAT));
                    }

                    VatwithoutSetupFee = (decimal)((finalamount / 100) * Convert.ToInt32(subscriptions.VAT));
                }
                decimal after_vat_totalamount = finalamount + Convert.ToDecimal(subscriptions.SetupFee) + Vat;

                // Send Email
                string body = string.Empty;
                _environment.WebRootPath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
                string contentRootPath = _environment.WebRootPath + "/htmltopdfP.html";
                string contentRootPath1 = _environment.WebRootPath + "/css/bootstrap.min.css";
                //Generate PDF
                using (StreamReader reader = new StreamReader(contentRootPath))
                {
                    body = reader.ReadToEnd();
                }
                //Fill EMail By Parameter
                body = body.Replace("{title}", "Tamarran Payment Invoice");
                body = body.Replace("{currentdate}", DateTime.UtcNow.ToString("yyyy-MM-dd hh:mm:ss tt"));

                body = body.Replace("{InvocieStatus}", "Unpaid");
                body = body.Replace("{InvoiceID}", "Inv" + invoiceinfo.InvoiceId);

                body = body.Replace("{User_Name}", applicationUser.FullName);
                body = body.Replace("{User_Email}", applicationUser.Email);

TapPaymentIntegration/Views/Home/AddCustomer.cshtml
@model TapPaymentIntegration.Areas.Identity.Data.ApplicationUser
@using Microsoft.Extensions.Configuration
@inject IConfiguration con;
@{
    string googleCaptchaKey = con.GetSection("GoogleCaptcha")["SiteKey"];
    ViewData["Title"] = "AddCustomer";
    Layout = "~/Views/Shared/_IdentityLayout.cshtml";
}
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="#" class="h1"><b>Tamarran</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">Sign up to Enter in Tamarran</p>
            @using (Html.BeginForm("AddCustomer", "Home", FormMethod.Post, new { id = "AddCustomer" }))
                {
                    <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="GYMName" placeholder="Enter The GYM Name" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-users"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="FullName" placeholder="Enter The Name" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-users"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" asp-for="UserName" placeholder="Enter The Email" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <span style="color:red!important">Enter Phone Number Without Country Code</span>
                <br />
                <div class="input-group mb-3">
                    <input type="number" class="form-control" asp-for="PhoneNumber" placeholder="Enter The Phone Number" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <select name="Country" class="form-control" id="Country" asp-for="Country" required="required">
                        <option value=" " label="Select a Country" selected="selected">Select a Country</option>
                        <option value="Bahrain" label="Bahrain">Bahrain</option>
                        <option value="KSA" label="KSA">KSA</option>
                        <option value="Kuwait" label="Kuwait">Kuwait</option>
                        <option value="UAE" label="UAE">UAE</option>
                        <option value="Qatar" label="Qatar">Qatar</option>
                        <option value="Oman" label="Oman">Oman</option>
                        </select>
                </div>
                <div class="input-group mb-3">
                    @Html.DropDownList("SubscribeID" ,(IEnumerable  <SelectListItem>)ViewBag.SubscriptionList, "Please Select Plan",new {  @class="form-control",@required="required",@onchange="fillfrequencyDropdown();"})
                </div>
                <div class="input-group mb-3">
                    <select class="form-control" id="Frequency" name="Frequency" required="required">
                        <option value="" label="Select a Frequency">Select a Frequency</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="City" placeholder="Enter The City" >
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-city"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="date" class="form-control" asp-for="InvoiceSendDate" placeholder="Select The Date">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-calendar"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input id="password-field" type="password" class="form-control" asp-for="Password" placeholder="Enter The Password" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-eye toggle-password" toggle="#password-field"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="g-recaptcha" data-sitekey="@googleCaptchaKey"></div>
                </div>
                <input type="hidden" id="recaptchaResponse" name="token" asp-for="recaptchaToken" />
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree" required="required">
                            <label for="agreeTerms">
                                I agree to the <a href="https://www.tamarran.com/En/content/Terms">terms</a>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="SignUp">Sign Up</button>
                    </div>
                    <!-- /.col -->
                </div>
            }
            <p class="mb-1">
                <div asp-validation-summary="All" class="text-danger"></div>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

    <partial name="_ValidationScriptsPartial" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script>
        $(".toggle-password").click(function () {

            $(this).toggleClass("fa-eye fa-eye-slash");
            if ($('#password-field').attr("type") == "password") {
                $('#password-field').attr("type", "text");
            }
            else {
                $('#password-field').attr("type", "password");
            }
        });

        function fillfrequencyDropdown()
        {
            var val = $("#SubscribeID").val();
            if (val != "") 
            {
                var formd = new FormData();
                formd.append("Frequency", val);
                $.ajax({
                    type: "POST",
                    url: "/Home/getFrequency",
                    processData: false,
                    contentType: false,
                    data: formd,
                    success: function (data) {
                        var dropdown = $('#Frequency');
                        dropdown.empty();
                        var result = data.Frequency;
                        var array = result.split(",");
                        debugger
                        var dllist = $('#Frequency');

                        $.each(array, function (i) {
                            dllist.append(
                                $('<option></option>').val(array[i]).html(array[i]));

                        });
                    }
                });
            }
            else 
            {
            var dropdown = $('#Frequency');
            dropdown.empty();
            }

    }

    document.getElementById('AddCustomer').addEventListener('submit', function (event) {
        var response = grecaptcha.getResponse();
        if (response.length == 0) {
            // reCAPTCHA not verified
            event.preventDefault();
            alert('Please verify reCAPTCHA');
        } else {
            // Set reCAPTCHA response in hidden input
            document.getElementById('recaptchaResponse').value = response;
        }
    });
    </script>

TapPaymentIntegration/Views/Home/CreateInvoice.cshtml
@model IEnumerable<TapPaymentIntegration.Models.InvoiceDTO.Invoice>
@{
    ViewData["Title"] = "CreateInvoice";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<br />
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header" style="padding: 0.5rem 1.25rem;">
                        <h4 class="text-center mb-0">Invoice List</h4>
                    </div>
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped table-responsive-xl">
                            <thead>
                                <tr style="text-align:center!important">
                                    <th>Invoice Start Date</th>
                                    <th>Invoice End Date</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th>Subscription Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in Model)
                                {
                                    <tr>
                                        <td style="text-align:center!important">
                                            @{
                                                DateTime sdateTime = Convert.ToDateTime(user.InvoiceStartDate);
                                                <span>@sdateTime.ToShortDateString()</span>
                                            }
                                        </td>
                                        <td style="text-align:center!important">
                                            @{
                                                DateTime edateTime = Convert.ToDateTime(user.InvoiceEndDate);
                                                <span>@edateTime.ToShortDateString()</span>
                                            }
                                        </td>
                                        <td style="text-align:center!important">@user.SubscriptionAmount</td>
                                        @if (user.Status == "Payment Captured")
                                        {
                                            <td style="text-align:center!important;color:green!important">@user.Status</td>
                                        }
                                        else
                                        {
                                        <td style="text-align:center!important">@user.Status</td>
                                        }
                                        <td style="text-align:center!important">@user.SubscriptionName</td>
                                        <td style="text-align:center!important">
                                            @if (user.Status != "Payment Captured")
                                            {
                                                <a class="btn btn-primary" href="@Url.Action("Index","TapPayment",new {id = user.InvoiceId, userid = user.UserId})">Pay Invoice</a>
                                                <a class="btn btn-danger" href="@Url.Action("DeleteInvoice","Home",new {id = user.InvoiceId, userid = user.UserId})">Delete Invoice</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,

            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>

TapPaymentIntegration/Views/Home/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@using TapPaymentIntegration.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@{
    string displayName = "";
    var UserType = "";
    var user = await UserManager.GetUserAsync(User);
    if (user == null)
    {
        displayName = User.Identity.Name;
        UserType = "Customer";
    }
    else
    {
        UserType = user.UserType;
        displayName = user.FullName;
    }
}
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<br />
@if (UserType != "Customer")
{
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="chart">
                                <div id="cvchartContainer" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="chart">
                                <div id="chartContainer" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@ViewBag.CustomerCount</h3>

                            <p>Customer</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person"></i>
                        </div>
                        <a href="@Url.Action("ViewCustomer","Home")" class="small-box-footer">View Customer<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@ViewBag.InvoiceCount</h3>

                            <p>All Invoices</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                        <a href="@Url.Action("ShowInvoice", "Home", new { PaymentStatus = "All" })" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@ViewBag.ChangeCardCount</h3>

                            <p>Change Card</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="@Url.Action("ViewChangeCardInfo","TapPayment")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>@ViewBag.SubscriptionCount</h3>

                            <p>Subscription Plan</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="@Url.Action("Viewsubscription","Home")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-primary">
                        <div class="inner">
                            <h3>@ViewBag.Paid</h3>

                            <p>Paid Invoices</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                        <a href="@Url.Action("ShowInvoice", "Home", new { PaymentStatus = "Payment Captured" })" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>@ViewBag.UnPaid</h3>

                            <p>Unpaid Invoices</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                        <a href="@Url.Action("ShowInvoice", "Home", new { PaymentStatus = "Un-Paid" })" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script>
    window.onload = function () {
        // weekly Chart
        var charts = new CanvasJS.Chart("cvchartContainer", {
            theme1: "light2", // "light1", "light2", "dark1", "dark2"
            animationEnabled: true,
            exportEnabled: true,
            toolTip: {
                shared: true
            },
            title: {
                text: "All Leads"
            },
            axisX: {
                gridThickness: 2,
                crosshair: {
                    enabled: true,
                    snapToDataPoint: true
                }
            },
            axisY: {
                title: "Leads Range",
                gridThickness: 2
            },
            data: [{
                type: "line",
                name: "Month",
                showInLegend: true,
                dataPoints: @Html.Raw(ViewBag.DataPoints1)
                                                }]
        });
        charts.render();



        var chart = new CanvasJS.Chart("chartContainer", {
            theme: "light2", // "light1", "light2", "dark1", "dark2"
            exportEnabled: true,
            animationEnabled: true,
            title: {
                text: "All Invoice Status"
            },

            data: [{
                type: "pie",
                startAngle: 180,
                toolTipContent: "<b>{label}</b>: {y}%",
                showInLegend: "true",
                legendText: "{label}",
                indexLabel: "{label} - {y}%",
                dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
        });
        chart.render();
    }
</script>

TapPaymentIntegration/Views/Home/ResumeRecurring.cshtml
@{
    ViewData["Title"] = "ResumeRecurring";
}